language: java
jdk:
  - oraclejdk8

install:
  - bash install.sh

before_deploy:
  - ls

deploy:
  skip_cleanup: true
  provider: heroku
  api_key: 2017f699-116e-4f4d-885b-f0532bc6613e
  file: target/UutisLukija-1.0-SNAPSHOT-jar-with-dependencies.jar
  app: uutislukija

after_deploy:
  - ls
