language: java

before_install:
  - git clone https://github.com/hy-ohtu/PaivanUutiset.git
  - git clone https://github.com/hy-ohtu/HackerNewsUutiset
  - cd PaivanUutiset && mvn install
  - cd ../HackerNewsUutiset && mvn install

after_success:
  - mvn clean cobertura:cobertura coveralls:report
